### ISSUE TITLE
Does it only work for 1.20.1 and lower?

### ISSUE THREAD

**Issue by Cryenq** [ZigyTheBird/ZigysPlayerAnimatorAPI#3]
I am new to minecraft mod programming and I managed to add kosmx library but I always fail. My Minecraft mod is currently 1.20.2 should it be able to use the api on this version or not?

**Comment by ZigyTheBird** [comment]
Hello there
1.20.1 mods aren't supported on 1.20.2+ but a 1.20.4 port is coming which might work for you (Or worst case scenario you can update to 1.20.4)
I am done coding the port I just need to fix a bug and then it will be released

**Comment by ZigyTheBird** [comment]
I will notify you here when it's out

**Comment by Cryenq** [comment]
Alright I see, so it was the version.
Thank you for porting and thank you for this library.

**Comment by ZigyTheBird** [comment]
Glad you like the library :)
The 1.20.4 port is out if you encounter any bugs please open an issue here
Contact me on discord if you need any help my username is zigythebird
